### ISSUE TITLE
Workflow subgraph bug

### ISSUE THREAD

**Issue by potavin** [jacebenson/workflow#5]
Good day.
**Problem**: problems with mapping workflow on unexpected flow input in subgraphs.
**How to reproduce**: open any standart workflow with subgraphs. For ex. 'Flow Top to Bottom'. Add new string before the end of subgraph, and print 4 spaces. Push 'Update'.

```
subgraph Fulfiller Task
    FTAssigned[Task Assigned to Group]-->FTEmailGroup[Email To Group]
    FTEmailGroup-->TaskComplete[Task Complete]
    
  end
```
Visual part disappears. Delete this string. Workflow now appears in the downside of the page. Some words doesn't normally displaying.
Don't reload the page. Open another workflow: Sequence Diagram
There is view collapse here.

**Comment by jacebenson** [comment]
I added code to disregard empty lines when rendering.  This bug is fixed
