### ISSUE TITLE
Arrow appearance problem

### ISSUE THREAD

**Issue by potavin** [jacebenson/workflow#7]
Good day.
Tested workflow, found one bug. Arrow end off and starts incorrectly.
Easy way to reproduce:
```
graph LR
  S0(Start)
  T1(Task 1)
  T2(Task 2)
  E0(End)
  
  S0-->E0
  S0-->T2
  T1-->E0
  T2-->E0

```

**Comment by jacebenson** [comment]
Yep, not sure what the expected output is here.

**Comment by jacebenson** [comment]
Can you clarify what you're seeing, and what you would expect?

**Comment by jacebenson** [comment]
https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFJcbiAgUzAoU3RhcnQpXG4gIFQxKFRhc2sgMSlcbiAgVDIoVGFzayAyKVxuICBFMChFbmQpXG4gIFxuICBTMC0tPkUwXG4gIFMwLS0-VDJcbiAgVDEtLT5FMFxuICBUMi0tPkUwIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0

It could just be the spacing of my elements around the mermaidjs section

**Comment by potavin** [comment]
Hm... Looks like some styles cover up some part of an arrow.
Correctly works with: <div class="mermaid" style="height: 250px;">

Just tested functional and show it to colleagues. Changed this thread name to more clear

**Comment by jacebenson** [comment]
I more closely cloned from mermaid live editor, are you still getting this arrow issues?
